PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX mg3: <https://w3id.org/moneygraph/ns/data/>
PREFIX gist: <https://w3id.org/semanticarts/ns/ontology/gist/>
PREFIX mg: <https://w3id.org/moneygraph/ns/ontology/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX mgx: <https://w3id.org/moneygraph/ns/taxonomy/>

SELECT 
?maturityyear
(SUM(?amt) AS ?peryear)

FROM mg3:__securities__latest
where {
    [] a gist:ScheduledEvent ;
        mg:plannedOccursDate ?repaydatetime ;
        gist:hasMagnitude [ gist:numericValue ?amt ] ;
        gist:isCharacterizedAs  mgx:_FinancialBusinessEventType_debtPrincipalRepayment .
    BIND(YEAR(?repaydatetime) AS ?maturityyear)

} GROUP BY ?maturityyear 
ORDER BY ASC(?maturityyear)